kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-cm
  namespace: nginx-ns
data:
  index.html: |
    <html>
      <head>
        <title>Welcome to nginx!</title>
      </head>
      <body>
        <h1>Success! The nginx server is working!</h1>
      </body>
    </html>
